### ISSUE TITLE
"make test" command produces errors, No module named '_opendbpy' and No such file or directory: './work/T6_PSI_settings.obj'

### ISSUE THREAD

**Issue by thesukantadey** [The-OpenROAD-Project/OpeNPDN#3]
Hi, earlier I installed OpeNPDN in some other system successfully. However, now I am getting error and not able to fix it. I am getting error after executing "make test". Can you help me in getting rid of the errors?

It is basically not able to find `/home/sukanta/github/OpeNPDN/./build/modules/OpenDB/src/swig/python/opendbpy.py` file and `./work/T6_PSI_settings.obj` file.
```

(env3) sukanta@sukanta:~/github/OpeNPDN$ make test
****************************************************************
************* Creating the defined templates *******************
****************************************************************
Traceback (most recent call last):
  File "./src/T6_PSI_settings.py", line 377, in <module>
    spec.loader.exec_module(odb)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sukanta/github/OpeNPDN/./build/modules/OpenDB/src/swig/python/opendbpy.py", line 15, in <module>
    import _opendbpy
ModuleNotFoundError: No module named '_opendbpy'
Traceback (most recent call last):
  File "./src/create_template.py", line 400, in <module>
    main()
  File "./src/create_template.py", line 394, in main
    create_templates()
  File "./src/create_template.py", line 182, in create_templates
    settings_obj = T6_PSI_settings.load_obj()
  File "/home/sukanta/github/OpeNPDN/src/T6_PSI_settings.py", line 176, in load_obj
    file = open("./work/T6_PSI_settings.obj",'rb')
FileNotFoundError: [Errno 2] No such file or directory: './work/T6_PSI_settings.obj'
****************************************************************
**** Creating the maps for training data generation ************
****************************************************************
Traceback (most recent call last):
  File "./scripts/create_training_set.py", line 11, in <module>
    settings_obj = T6_PSI_settings.load_obj();
  File "/home/sukanta/github/OpeNPDN/src/T6_PSI_settings.py", line 176, in load_obj
    file = open("./work/T6_PSI_settings.obj",'rb')
FileNotFoundError: [Errno 2] No such file or directory: './work/T6_PSI_settings.obj'
****************************************************************
******** Running golden data generation  ***********************
****************************************************************
Traceback (most recent call last):
  File "./src/generate_training_data_iterative.py", line 145, in <module>
    main()
  File "./src/generate_training_data_iterative.py", line 14, in main
    settings_obj = T6_PSI_settings.load_obj()
  File "/home/sukanta/github/OpeNPDN/src/T6_PSI_settings.py", line 176, in load_obj
    file = open("./work/T6_PSI_settings.obj",'rb')
FileNotFoundError: [Errno 2] No such file or directory: './work/T6_PSI_settings.obj'
make: *** [Makefile:181: test] Error 1
```

**Comment by VidyaChhabria** [comment]
Thanks for pointing it out. Sure I will be able to fix this. It needs a little bit of cleaning to the README and code. I am a little busy with a few things right now and I will be able to get to this next Friday only though.

**Comment by thesukantadey** [comment]
Thanks for your prompt reply.

**Comment by thesukantadey** [comment]
Hey @VidyaChhabria , any update on this?

**Comment by thesukantadey** [comment]
Hi @VidyaChhabria, can you help me resolve the issue I posted here? Do we need to install OpenDB explicitly and use its location in OpeNPN? I even tried changing the Makefiles. However, not able to resolve the issue. Any help in this regard will be helpful.

Another issue is that I am not able to find `T6_PSI_settings.obj` file in the work directory. I am not sure if the cmake builds it correctly or what's wrong. Please help.
